services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_NAME=todo

      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=todo_user
      - DB_PASSWORD=todo_password

      - DB_READ_HOST=postgres
      - DB_READ_PORT=5432
      - DB_READ_USER=todo_user
      - DB_READ_PASSWORD=todo_password

      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
